import click
import pandas as pd
from pathlib import Path
from rich.console import Console

from traincli.utils.display import banner, header, success, warn, error, info, blank
from traincli.utils.session import Session
from traincli.profiler import profile
from traincli.cleaner import clean
from traincli.detector import detect
from traincli.trainer import train, improve
from traincli.exporter import export

console = Console()


@click.command()
def init():
    """Set up TrainCLI with your API credentials."""
    from rich.console import Console
    from rich.panel import Panel
    import os
    from pathlib import Path

    console = Console()
    console.print(Panel.fit(
        "[bold cyan]TrainCLI Setup[/bold cyan]",
        border_style="cyan"
    ))

    provider = click.prompt(
        "LLM Provider",
        type=click.Choice(["watsonx", "groq", "none"]),
        default="watsonx"
    )

    config = {}

    if provider == "watsonx":
        config["WATSONX_API_KEY"] = click.prompt("WatsonX API Key", hide_input=True)
        config["WATSONX_PROJECT_ID"] = click.prompt("WatsonX Project ID")
        config["WATSONX_URL"] = click.prompt(
            "WatsonX URL",
            default="https://us-south.ml.cloud.ibm.com"
        )
        config["LLM_MODEL"] = "ibm/granite-13b-instruct-v2"
        config["LLM_PROVIDER"] = "watsonx"

    elif provider == "groq":
        config["GROQ_API_KEY"] = click.prompt("Groq API Key", hide_input=True)
        config["LLM_MODEL"] = "llama-3.3-70b-versatile"
        config["LLM_PROVIDER"] = "groq"

    if provider != "none":
        # Save to ~/.traincli/config.env
        config_dir = Path.home() / ".traincli"
        config_dir.mkdir(exist_ok=True)
        config_file = config_dir / "config.env"

        with open(config_file, "w") as f:
            f.write("# TrainCLI Configuration\n")
            f.write("# Generated by train init\n\n")
            for k, v in config.items():
                f.write(f"{k}={v}\n")

        console.print(f"\n[bold green]✓[/bold green] Config saved to {config_file}")

    console.print("[bold green]✓[/bold green] TrainCLI is ready.")
    console.print("  Run: [cyan]train --data ./data.csv --target column[/cyan]")


@click.command()
@click.option("--data",    "-d", default=None, help="Path to CSV file")
@click.option("--dir",     "-D", "data_dir", default=None, help="Directory of CSV files")
@click.option("--target",  "-t", required=True, help="Target column name")
@click.option("--model",   "-m", default=None, help="Model key, or '?' to pick interactively")
@click.option("--task",          default=None, type=click.Choice(["classification", "regression"]), help="Override problem type detection")
@click.option("--improve",       "improve_model", default=None, help="Path to existing model.pkl to retrain")
@click.option("--out",     "-o", default="./output", help="Output directory (default: ./output)")
@click.option("--preview",       is_flag=True, help="Preview without training")
@click.option("--auto",          is_flag=True, help="Skip interactive prompts")
@click.option("--meta",          is_flag=True, help="Collect metadata for meta-model training")
@click.option("--no-llm",        is_flag=True, help="Skip all LLM calls (faster, no API quota used)")
def main(data, data_dir, target, model, task, improve_model, out, preview, auto, meta, no_llm):
    """
    TrainCLI — train ML models from a single command.

    \b
    Examples:
      train --data ./sales.csv --target churn
      train --data ./sales.csv --target price --model random_forest
      train --data ./sales.csv --target price --model ?
      train --data ./sales.csv --target churn --task classification
      train --improve ./output/model.pkl --data ./new_data.csv --target churn
      train --dir ./datasets/ --target label
      train --data ./sales.csv --target churn --preview
    """
    banner()

    # ── IMPROVE MODE ─────────────────────────────────────────
    if improve_model:
        if not data:
            error("--improve requires --data pointing to new training data")
            raise click.Abort()
        session = Session(data, target)
        results = improve(improve_model, data, target, session)
        output_dir = Path(out)
        output_dir.mkdir(parents=True, exist_ok=True)

        import pickle
        model_path = output_dir / "model.pkl"
        with open(model_path, "wb") as f:
            pickle.dump(results["pipeline"], f)
        success(f"Improved model saved → {model_path}")
        return

    # ── VALIDATE ─────────────────────────────────────────────
    if not data and not data_dir:
        error("Provide --data (single file) or --dir (folder)")
        raise click.Abort()

    if data and data_dir:
        error("Provide either --data or --dir, not both")
        raise click.Abort()

    # ── DISPATCH ─────────────────────────────────────────────
    if data_dir:
        _run_folder(data_dir, target, model, task, out, auto, meta, no_llm)
    else:
        _run_single(data, target, model, task, out, preview, auto, meta, no_llm)


def _run_single(data_path, target, model_key, task, out, preview, auto, meta=False, no_llm=False):
    path = Path(data_path)
    if not path.exists():
        error(f"File not found: {data_path}")
        raise click.Abort()

    # Disable LLM calls if --no-llm flag set
    if no_llm:
        import os
        os.environ["TRAINCLI_NO_LLM"] = "1"

    # Load
    header("Loading dataset")
    try:
        df = pd.read_csv(path)
    except Exception as e:
        error(f"Could not read CSV: {e}")
        raise click.Abort()

    if target not in df.columns:
        error(f"Target '{target}' not found. Available: {list(df.columns)}")
        raise click.Abort()

    info(f"Loaded {len(df):,} rows × {len(df.columns)} columns from {path.name}")

    session = Session(data_path, target)

    # Profile
    prof = profile(df, target)
    session.set_profile({
        "rows": prof["rows"],
        "cols": prof["cols"],
        "null_pct": prof["null_pct"],
        "issues_found": len(prof["issues"]),
    })

    # Auto-drop leaky columns in auto mode
    if prof.get("leakage"):
        leaky_cols = [s["col"] for s in prof["leakage"]]
        if auto:
            df = df.drop(columns=leaky_cols, errors="ignore")
            for col in leaky_cols:
                success(f"Auto-dropped leaky column: '{col}'")
        # In interactive mode the panel already showed — user decides via --drop

    # Preview
    if preview:
        blank()
        _print_preview(df, prof, target, model_key)
        return

    # Clean
    df_clean = clean(df, prof, session, auto=auto)

    # Detect problem type
    if task:
        # User override
        from traincli.utils.display import success as disp_success
        disp_success(f"Problem type: [bold]{task}[/bold]  [dim](manually specified)[/dim]")
        session.set_problem(task, "user_flag")
        problem_type = task
    else:
        problem_type = detect(df_clean, target, session)

    # Train
    results = train(
        df=df_clean,
        target=target,
        problem_type=problem_type,
        session=session,
        model_key=model_key,
        interactive=not auto,
        profile=prof,
    )

    # Export
    output_dir = Path(out)
    export(results, df_clean, target, data_path, output_dir, session)

    # Meta collection
    if meta:
        try:
            from traincli.meta_collector import collect
            row = collect(df_clean, target, results)
            success(f"Meta row collected → ~/.traincli/meta_dataset.csv")
        except Exception as e:
            warn(f"Meta collection failed: {e}")

    blank()
    console.print("[bold green]Done![/bold green]")
    console.print(f"  Output : [cyan]{output_dir.resolve()}[/cyan]")
    console.print(f"  Files  : model.pkl · train.py · report.md · metrics.json · session.json")
    blank()


def _run_folder(data_dir, target, model_key, task, out, auto, meta=False, no_llm=False):
    from rich.table import Table
    from rich import box

    # Disable LLM calls if --no-llm flag set
    if no_llm:
        import os
        os.environ["TRAINCLI_NO_LLM"] = "1"

    folder = Path(data_dir)
    if not folder.exists() or not folder.is_dir():
        error(f"Directory not found: {data_dir}")
        raise click.Abort()

    csv_files = list(folder.glob("*.csv"))
    if not csv_files:
        error(f"No CSV files found in {data_dir}")
        raise click.Abort()

    info(f"Found {len(csv_files)} CSV file(s)")
    blank()

    summary_rows = []
    output_base = Path(out)

    for csv_path in csv_files:
        console.rule(f"[cyan]{csv_path.name}[/cyan]")
        sub_out = output_base / csv_path.stem

        try:
            df = pd.read_csv(csv_path)
            if target not in df.columns:
                warn(f"Target '{target}' not found in {csv_path.name} — skipping")
                summary_rows.append({"file": csv_path.name, "status": "skipped", "model": "-", "score": "-", "confidence": "-"})
                continue

            session = Session(str(csv_path), target)
            prof = profile(df, target)
            session.set_profile({"rows": prof["rows"], "cols": prof["cols"], "null_pct": prof["null_pct"], "issues_found": len(prof["issues"])})
            df_clean = clean(df, prof, session, auto=True)

            if task:
                problem_type = task
                session.set_problem(task, "user_flag")
            else:
                problem_type = detect(df_clean, target, session)

            results = train(df_clean, target, problem_type, session, model_key=model_key, interactive=False, profile=prof)
            export(results, df_clean, target, str(csv_path), sub_out, session)

            # Meta collection
            if meta:
                try:
                    from traincli.meta_collector import collect
                    collect(df_clean, target, results)
                except Exception as e:
                    warn(f"Meta collection failed for {csv_path.name}: {e}")

            primary = list(results["metrics"].values())[0]
            summary_rows.append({
                "file": csv_path.name,
                "status": "done",
                "model": results["model_entry"]["label"],
                "score": primary,
                "confidence": results["confidence"],
            })

        except Exception as e:
            error(f"Failed on {csv_path.name}: {e}")
            summary_rows.append({"file": csv_path.name, "status": "error", "model": "-", "score": "-", "confidence": "-"})

    # Summary table
    blank()
    console.rule("[bold]Summary[/bold]")
    blank()
    table = Table(box=box.SIMPLE, show_header=True, header_style="bold")
    table.add_column("File")
    table.add_column("Status")
    table.add_column("Model")
    table.add_column("Score")
    table.add_column("Confidence")

    for row in summary_rows:
        s = row["status"]
        color = "green" if s == "done" else "red" if s == "error" else "yellow"
        table.add_row(row["file"], f"[{color}]{s}[/{color}]", row["model"], row["score"], row["confidence"])

    console.print(table)
    _write_folder_summary(summary_rows, output_base, target)
    success(f"summary.md → {output_base / 'summary.md'}")
    blank()


def _print_preview(df, prof, target, model_key):
    console.print("[bold]Preview mode — nothing will be trained[/bold]")
    blank()
    console.print(f"  Dataset : {prof['rows']:,} rows × {prof['cols']} columns")
    console.print(f"  Target  : {target}")
    auto   = sum(1 for i in prof["issues"] if i["auto_fixable"])
    manual = len(prof["issues"]) - auto
    console.print(f"  Issues  : {len(prof['issues'])} found ({auto} auto-fix, {manual} need input)")
    console.print(f"  Model   : {'auto-select via CV' if not model_key or model_key == '?' else model_key}")
    blank()
    console.print("Run without [cyan]--preview[/cyan] to train.")


def _write_folder_summary(rows, output_dir, target):
    output_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "# TrainCLI — Folder Run Summary",
        "",
        f"**Target:** `{target}`  ",
        f"**Generated:** {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "| File | Status | Model | Score | Confidence |",
        "|------|--------|-------|-------|------------|",
    ]
    for row in rows:
        lines.append(f"| {row['file']} | {row['status']} | {row['model']} | {row['score']} | {row['confidence']} |")

    with open(output_dir / "summary.md", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()