import os
from pathlib import Path
from rich.console import Console
from rich.prompt import Prompt

console = Console()


def get_config_path() -> Path:
    """Get the path to the global config file."""
    home = Path.home()
    config_dir = home / ".traincli"
    config_dir.mkdir(exist_ok=True)
    return config_dir / "config.env"


def init_config():
    """Interactive setup wizard for TrainCLI configuration."""
    console.print("\n[bold cyan]TrainCLI Setup[/bold cyan]")
    console.print("─" * 40)
    
    # Ask for LLM provider
    provider = Prompt.ask(
        "LLM Provider",
        choices=["watsonx", "groq", "none"],
        default="watsonx"
    )
    
    config_lines = [
        "# TrainCLI Configuration",
        "# Generated by: train init",
        "",
        f"LLM_PROVIDER={provider}",
    ]
    
    if provider == "watsonx":
        api_key = Prompt.ask("WatsonX API Key", password=True)
        project_id = Prompt.ask("WatsonX Project ID")
        url = Prompt.ask(
            "WatsonX URL",
            default="https://us-south.ml.cloud.ibm.com"
        )
        
        config_lines.extend([
            f"WATSONX_API_KEY={api_key}",
            f"WATSONX_PROJECT_ID={project_id}",
            f"WATSONX_URL={url}",
            "LLM_MODEL=meta-llama/llama-3-3-70b-instruct",
        ])
    
    elif provider == "groq":
        api_key = Prompt.ask("Groq API Key", password=True)
        config_lines.extend([
            f"GROQ_API_KEY={api_key}",
            "LLM_MODEL=llama-3.1-70b-versatile",
        ])
    
    else:
        config_lines.append("# No LLM provider configured — offline mode")
    
    # Write config
    config_path = get_config_path()
    with open(config_path, "w") as f:
        f.write("\n".join(config_lines))
    
    console.print(f"\n[green]✓[/green] Config saved to [cyan]{config_path}[/cyan]")
    console.print("[green]✓[/green] Run: [bold]train --data ./data.csv --target column[/bold]\n")


def load_config():
    """Load configuration from global config file if it exists."""
    config_path = get_config_path()
    if config_path.exists():
        from dotenv import load_dotenv
        load_dotenv(config_path)

# Made with Bob
